/*
 * DIO_config.h
 *
 *  Created on: Oct 3, 2023
 *      Author: Alaraby
 */
#ifndef  DIO_CONFIG_H_
#define  DIO_CONFIG_H_

#define PORTA_PIN0_DIR INPUT
#define PORTA_PIN1_DIR INPUT
#define PORTA_PIN2_DIR OUTPUT
#define PORTA_PIN3_DIR OUTPUT
#define PORTA_PIN4_DIR INPUT
#define PORTA_PIN5_DIR INPUT
#define PORTA_PIN6_DIR OUTPUT
#define PORTA_PIN7_DIR INPUT

#define PORTB_PIN0_DIR INPUT
#define PORTB_PIN1_DIR INPUT
#define PORTB_PIN2_DIR OUTPUT
#define PORTB_PIN3_DIR OUTPUT
#define PORTB_PIN4_DIR INPUT
#define PORTB_PIN5_DIR INPUT
#define PORTB_PIN6_DIR OUTPUT
#define PORTB_PIN7_DIR INPUT

#define PORTC_PIN0_DIR INPUT
#define PORTC_PIN1_DIR INPUT
#define PORTC_PIN2_DIR OUTPUT
#define PORTC_PIN3_DIR OUTPUT
#define PORTC_PIN4_DIR INPUT
#define PORTC_PIN5_DIR INPUT
#define PORTC_PIN6_DIR OUTPUT
#define PORTC_PIN7_DIR INPUT

#define PORTD_PIN0_DIR INPUT
#define PORTD_PIN1_DIR INPUT
#define PORTD_PIN2_DIR OUTPUT
#define PORTD_PIN3_DIR OUTPUT
#define PORTD_PIN4_DIR INPUT
#define PORTD_PIN5_DIR INPUT
#define PORTD_PIN6_DIR OUTPUT
#define PORTD_PIN7_DIR INPUT

#define PORTA_PIN0_VAL LOW
#define PORTA_PIN1_VAL LOW
#define PORTA_PIN2_VAL HIGH
#define PORTA_PIN3_VAL FLOAT
#define PORTA_PIN4_VAL HIGH
#define PORTA_PIN5_VAL PULLUP
#define PORTA_PIN6_VAL PULLUP
#define PORTA_PIN7_VAL FLOAT

#define PORTB_PIN0_VAL LOW
#define PORTB_PIN1_VAL LOW
#define PORTB_PIN2_VAL HIGH
#define PORTB_PIN3_VAL FLOAT
#define PORTB_PIN4_VAL HIGH
#define PORTB_PIN5_VAL PULLUP
#define PORTB_PIN6_VAL PULLUP
#define PORTB_PIN7_VAL FLOAT

#define PORTC_PIN0_VAL LOW
#define PORTC_PIN1_VAL LOW
#define PORTC_PIN2_VAL HIGH
#define PORTC_PIN3_VAL FLOAT
#define PORTC_PIN4_VAL HIGH
#define PORTC_PIN5_VAL PULLUP
#define PORTC_PIN6_VAL PULLUP
#define PORTC_PIN7_VAL FLOAT

#define PORTD_PIN0_VAL LOW
#define PORTD_PIN1_VAL LOW
#define PORTD_PIN2_VAL HIGH
#define PORTD_PIN3_VAL FLOAT
#define PORTD_PIN4_VAL HIGH
#define PORTD_PIN5_VAL PULLUP
#define PORTD_PIN6_VAL PULLUP
#define PORTD_PIN7_VAL FLOAT

#endif

